Upgrade additional packages
Sitefinity/Sitefinity-CLI pull request #183
Opened 2022-04-13 11:14 UTC by ElenaZarkova

2022-04-14 05:35 UTC, RuzmanovDev commented
Lets bump the version of the CLI. There are two parameters in the .csproj file

2022-04-14 12:31 UTC, yasen-yankov approved these changes

2022-04-14 12:33 UTC, RuzmanovDev approved these changes

2022-04-14 13:23 UTC, RuzmanovDev requested changes

2022-04-14 13:23 UTC, RuzmanovDev commented on Sitefinity CLI/Commands/UpgradeCommand.cs
> -    [AdminRightsValidator]
Maybe we should delete the class as well

2022-04-15 05:29 UTC, RuzmanovDev approved these changes

2022-04-18 08:26 UTC, merged