Upgrade the .Net Core framework to 6.0 and other libraries to the lastest stable versions
Sitefinity/Sitefinity-CLI pull request #194
Opened 2022-07-05 10:18 UTC by bkirpiev

2022-07-11 05:02 UTC, RuzmanovDev requested changes

2022-07-11 05:02 UTC, RuzmanovDev commented on Sitefinity CLI/Sitefinity CLI.csproj
>      <AssemblyVersion>1.1.0.29</AssemblyVersion>
Lets bump the bersion to 1.1.0.30

2022-11-11 12:15 UTC, RuzmanovDev approved these changes
LGTM

2023-01-04 12:00 UTC, NTonchev approved these changes

2023-01-04 12:08 UTC, merged