Added sanitization when creating a resource package folder
Sitefinity/Sitefinity-CLI pull request #250
Opened 2023-04-13 10:37 UTC by bzlatano

2023-04-18 12:58 UTC, RuzmanovDev requested changes

2023-04-18 12:58 UTC, RuzmanovDev commented on Sitefinity CLI/Commands/AddResourcePackageCommand.cs
> +        internal string GetSanitizedName(string name)
this should be a private method

2023-04-18 12:58 UTC, RuzmanovDev commented on Sitefinity CLI/Commands/AddResourcePackageCommand.cs
> +                if ((cat != UnicodeCategory.UppercaseLetter) && (cat != UnicodeCategory.LowercaseLetter) &&
Maybe if we add the unsupported UnicodeCategories into a some kind of list and check if our is in it, it will be more readable

2023-04-18 12:58 UTC, RuzmanovDev commented on Sitefinity CLI/Commands/AddResourcePackageCommand.cs
> +            if (Char.IsDigit(name[0]))
Char.isDigit should be with lowercased - char.IsDigit

2023-04-18 12:58 UTC, RuzmanovDev commented on Sitefinity CLI/Commands/AddResourcePackageCommand.cs
Make sure to run the unit tests since there is no CI for the CLI

2023-04-19 12:57 UTC, bkirpiev approved these changes

2023-04-19 13:03 UTC, merged