Bzlatano/update test template
Sitefinity/Sitefinity-CLI pull request #283
Opened 2023-12-13 16:04 UTC by bzlatano

2023-12-13 16:09 UTC, RuzmanovDev requested changes

2023-12-13 16:09 UTC, RuzmanovDev commented on Sitefinity CLI/Templates/13.3/PageTemplate/Test.Template
> +    @Html.StyleSheet(Url.WidgetContent("~/ResourcePackages/Bootstrap4/assets/dist/css/main.min.css"), "head", true)
I think we should not include stylesheets.

2024-01-03 08:46 UTC, RuzmanovDev approved these changes

2024-01-03 09:05 UTC, bkirpiev approved these changes

2024-01-03 09:08 UTC, merged